extends Node2D

var regole = [
	#Nome; Trigger; Condizioni Aggiuntive; Sostituzione; Probabilità (deve essere ultima, modica in applica_regole)
	["base1", "TTT", ["-wA"], ["-wT"], 60.0],
	["base2", "TAT", [], ["TTT"], 100.0],
	["base3", "AT", ["-wAA","+w#T"], ["ArT"], 100.0],
	["base4", "TA", ["-wAA", "+w#T"], ["TRA"], 100.0],
	["room1", "AAAA", ["-w-1AAAA", "+w-1AAAA", "+w+w+w-1AAA", "-1A"], ["eS"], 0.5],
	["room2", "S", ["-w-1AAAAA","+w-1AAAAA", "+3A"], ["SSS"], 40.0],
	["room3", "SA", ["-w-1AAAA", "+w-1AAAA"], ["SE"], 100.0],
	["room4", "S", ["+1eS"], ["+1S"], 100.0],
	["room5", "A", ["-w-wS"], ["P"], 100.0],
	["room6", "A", ["-w-wE"], ["O"], 100.0],
	["room7", "A", ["-w-we"], ["O"], 100.0],
	["sostituzione S", "S", [], ["P"], 100.0],
	["piattaforme", "AAA", ["-w-1AAAAA", "+w-1AAAA", "-2AA"], ["PPP"], 15.0],
	["piattaforme espansione", "A", ["-w-1AAAA", "+w-1AAAA", "+1AA", "-1P"], ["P"], 60.0], 
	["edge1", "PA", ["+w-1AAA", "-w-1AAAA", "+2A"], ["PE"], 80.0],
	["edge2", "PA", ["+w-1AAA", "-w-1AAAA", "+w+wP", "+2A"], ["PE"], 100.0],
	["edge3", "AP", ["-w-1AAA", "-1A", "+w-1AAA"], ["eP"], 80.0],
	["edge4", "AP", ["-w-1AAA", "-1A", "+w-1AAA", "+w+wP"], ["eP"], 100.0],
	["ostacolo", "PPP", [], ["POP"], 20.0],
	["ostacolo", "PPP",[], ["PoP"], 20.0],
	["Nemico", "PO", [], ["N"], 10.0],
	["Nemico", "OP", [], ["+1N"], 10.0],
	["Nemico", "P", [], ["N"], 8.0],
	["verticale1", "A", ["-wE", "+wP", "+1A"], ["V"], 90.0],
	["verticale2", "A", ["-we", "+wP", "+1A"], ["V"], 90.0],
	["verticale3", "P", ["-wV"], ["O"], 70.0],
	["verticale4", "A", ["-wo", "+wA"], ["V"], 100.0],
] 

var lettere_to_texture ={
	"A" : preload("res://Textures/trasparente.png"),
	"T" : preload("res://Textures/nero.png"),
	"P" : preload("res://Textures/piattaforma.png"),
	"E" : preload("res://Textures/Edge_Sx.png"),
	"e" : preload("res://Textures/Edge_Dx.png"),
	"R" : preload("res://Textures/muro_ramp.png"),
	"r" : preload("res://Textures/muro_rampa_up.png"),
	"V" : preload("res://Textures/verticale.png"),
	"O" : preload("res://Textures/piattaforma_ostacolo.png"),
	"o" : preload("res://Textures/piattaforma_ostacolo_down.png"),
	"N" : preload("res://Textures/nemico.png"),
}
